[meta]
name     = "Editor++"
author   = "XertroV"
category = "Map Editor"
version  = "0.8.10"
siteid   = 377
blocks   = ["item-placement-toolbox", "item-placement-toolbox-dev"]

[script]
#__DEFINES__
dependencies = ["Camera"]
# some editor things can take a while, like saving the map
timeout  = 7500
