[meta]
name     = "Editor++"
author   = "XertroV"
category = "Map Editor"
version  = "0.8.9999991"
siteid   = 377
blocks   = ["item-placement-toolbox", "item-placement-toolbox-dev"]

[script]
#__DEFINES__
dependencies = ["Camera", "VehicleState"]
# optional_dependencies = ["MLHook"]
# some editor things can take a while, like saving the map
timeout  = 7500

shared_exports = ["GBX/GBX.as", "Editor/MacroblockManip_Shared.as"]
exports = ["Exports/Functions.as", "Editor/MacroblockManip_ExportCode.as"]

module = "Editor"
