[meta]
name     = "Editor++"
author   = "XertroV"
category = "Map Editor"
version  = "0.7.8.1"
siteid   = 377
blocks   = ["item-placement-toolbox", "item-placement-toolbox-dev"]

[script]
#__DEFINES__
dependencies = ["Camera"]
